
version: "2"
services:
  db:
    image: mongo
    ports:
      - "27018:27018"
  web:
     build: ./webapp
     command: python manage.py runserver 0.0.0.0:8000 
     volumes: 
       - ./webapp:/webapp
     ports: 
       - "8000:8000"
     depends_on:
       - db 

