# Generated by Django 2.1.7 on 2019-03-03 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('NumeroCuentaBancaria', models.IntegerField(primary_key=True, serialize=False)),
                ('saldo', models.DecimalField(decimal_places=4, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='ServiciosBancarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreServicio', models.CharField(max_length=30)),
                ('NumeroCuentaBancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inicio.CuentaBancaria')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Monto', models.DecimalField(decimal_places=4, max_digits=8)),
                ('FechaTransaccion', models.DateField()),
                ('CuentaDestino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='DestinoCuenta', to='inicio.CuentaBancaria')),
                ('CuentaOrigen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OrigenCuenta', to='inicio.CuentaBancaria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=30)),
                ('Apellido', models.CharField(max_length=30)),
                ('usuario', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.IntegerField()),
                ('Fecha_Creacion', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='cuentabancaria',
            name='UsuarioPropietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CuentaBancariaUsuario', to='inicio.Usuario'),
        ),
    ]
