# Generated by Django 2.1.7 on 2019-03-03 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_auto_20190303_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='DebitoCredito',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
