# Generated by Django 2.1.7 on 2019-03-03 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20190303_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=30),
        ),
    ]
