# Generated by Django 2.1.7 on 2019-03-03 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_auto_20190303_0319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
