# Generated by Django 2.1.7 on 2019-03-03 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_auto_20190303_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviciosbancarios',
            name='Usuario',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='inicio.Usuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='serviciosbancarios',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
