# Generated by Django 2.1.7 on 2019-03-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0007_auto_20190303_0646'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaccion',
            name='Decripcion',
            field=models.CharField(default=0, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='usuario',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='serviciosbancarios',
            name='NombreServicio',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Apellido',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='Nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='usuario',
            field=models.CharField(max_length=150),
        ),
    ]
